import type { Metadata } from "next";
import {  Poppins } from "next/font/google";
import "./globals.css";

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

// const satoshi = localFont({
//   variable: "--font-satoshi",
//   src: [
//     { path: "./fonts/Satoshi-Regular.woff2", weight: "400" },
//     { path: "./fonts/Satoshi-Medium.woff2", weight: "500" },
//     { path: "./fonts/Satoshi-Bold.woff2", weight: "700" },
//   ],
// });

export const metadata: Metadata = {
  title: "ByteSpace",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html  lang="en"  className={`${poppins.variable}  h-full antialiased`}>
      <body className="min-h-full flex flex-col">
        {children}
      </body>
    </html>
  );
}
